# Generated by Django 2.2 on 2019-05-10 12:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_usercustomview'),
    ]

    operations = [
        migrations.AddField(
            model_name='usercustomview',
            name='is_default',
            field=models.BooleanField(default=False),
        ),
    ]
