# Generated by Django 2.2 on 2019-07-24 10:53

import django.contrib.postgres.fields.jsonb
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_usercustomview_is_default'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usercustomview',
            name='application_listing_fields',
            field=django.contrib.postgres.fields.jsonb.JSONField(),
        ),
    ]
