# Generated by Django 2.2 on 2021-03-30 15:58

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('application', '0207_auto_20210330_1558'),
    ]

    operations = [
        migrations.CreateModel(
            name='Followup',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True, null=True)),
                ('blend_application_id', models.TextField()),
                ('blend_followup_id', models.TextField(unique=True)),
                ('followup_type', models.TextField(blank=True, null=True)),
                ('status', models.TextField(blank=True, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('requested_date', models.DateTimeField(blank=True, null=True)),
                ('application', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='followups', to='application.Application')),
                ('loan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='followups', to='application.Loan')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
