# Generated by Django 2.2 on 2021-04-01 17:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blend', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='followup',
            name='salesforce_id',
            field=models.TextField(blank=True, null=True, unique=True),
        ),
    ]
