# Generated by Django 2.2 on 2019-05-09 07:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0003_auto_20190508_1548'),
    ]

    operations = [
        migrations.AddField(
            model_name='application',
            name='agents_name',
            field=models.CharField(blank=True, max_length=225, null=True),
        ),
        migrations.AddField(
            model_name='application',
            name='has_lender',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='application',
            name='has_realestate_agent',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='application',
            name='lenders_email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='application',
            name='lenders_name',
            field=models.CharField(blank=True, max_length=225, null=True),
        ),
        migrations.AddField(
            model_name='application',
            name='lenders_phone_number',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='application',
            name='move_by_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='application',
            name='offer_address',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='application.Address'),
        ),
    ]
