# Generated by Django 2.2 on 2019-05-10 06:29

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0005_application_has_home_to_sell'),
    ]

    operations = [
        migrations.CreateModel(
            name='MortgageLender',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='RealEstateAgent',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.RemoveField(
            model_name='application',
            name='agents_name',
        ),
        migrations.RemoveField(
            model_name='application',
            name='has_home_to_sell',
        ),
        migrations.RemoveField(
            model_name='application',
            name='has_lender',
        ),
        migrations.RemoveField(
            model_name='application',
            name='has_realestate_agent',
        ),
        migrations.RemoveField(
            model_name='application',
            name='lenders_email',
        ),
        migrations.RemoveField(
            model_name='application',
            name='lenders_name',
        ),
        migrations.RemoveField(
            model_name='application',
            name='lenders_phone_number',
        ),
        migrations.RemoveField(
            model_name='application',
            name='offer_address',
        ),
        migrations.AddField(
            model_name='application',
            name='mortgage_lender',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='application.MortgageLender'),
        ),
        migrations.AddField(
            model_name='application',
            name='real_estate_agent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='application.RealEstateAgent'),
        ),
    ]
