# Generated by Django 2.2 on 2019-05-10 12:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0007_auto_20190510_1029'),
    ]

    operations = [
        migrations.AlterField(
            model_name='application',
            name='home_buying_stage',
            field=models.CharField(choices=[('researching online', 'researching online'), ('viewing listings in person', 'viewing listings in person'), ('making an offer', 'making an offer'), ('working with a builder', 'working with a builder')], max_length=50),
        ),
        migrations.AlterField(
            model_name='application',
            name='stage',
            field=models.CharField(choices=[('draft', 'draft'), ('complete', 'complete')], max_length=50),
        ),
    ]
