# Generated by Django 2.2 on 2019-05-13 14:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0008_auto_20190510_1252'),
    ]

    operations = [
        migrations.AddField(
            model_name='realestateagent',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='realestateagent',
            name='phone',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
