# Generated by Django 2.2 on 2019-05-21 06:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0009_auto_20190513_1404'),
    ]

    operations = [
        migrations.AlterField(
            model_name='application',
            name='builder',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='application.Builder'),
        ),
        migrations.AlterField(
            model_name='application',
            name='mortgage_lender',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='application.MortgageLender'),
        ),
        migrations.AlterField(
            model_name='application',
            name='real_estate_agent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='application.RealEstateAgent'),
        ),
    ]
