# Generated by Django 2.2 on 2019-05-20 18:48

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0009_auto_20190513_1404'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='currenthome',
            name='market_value',
        ),
        migrations.CreateModel(
            name='MarketValueAnalysis',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('mls', models.CharField(choices=[('GA_FMLS', 'GA_FMLS'), ('GA_MLS', 'GA_MLS'), ('TX_SABOR', 'TX_SABOR'), ('TX_HAR', 'TX_HAR'), ('TX_ACTRIS', 'TX_ACTRIS'), ('TX_NTREIS', 'TX_NTREIS'), ('CO_Metrolist', 'CO_Metrolist'), ('CO_IRES', 'CO_IRES')], max_length=50)),
                ('listing_id', models.CharField(blank=True, max_length=50, null=True)),
                ('property_condition', models.CharField(choices=[('Bad', 'Bad'), ('Ok', 'Ok'), ('Great', 'Great')], max_length=50)),
                ('suggested_list_price', models.IntegerField(blank=True, null=True)),
                ('minimum_sales_price', models.IntegerField(blank=True, null=True)),
                ('maximum_sales_price', models.IntegerField(blank=True, null=True)),
                ('sales_price_confidence', models.CharField(choices=[('High', 'High'), ('Medium', 'Medium'), ('Low', 'Low')], max_length=50)),
                ('estimated_days_on_market', models.CharField(blank=True, max_length=50, null=True)),
                ('is_in_completed_neighborhood', models.BooleanField(blank=True, null=True)),
                ('is_less_than_one_acre', models.BooleanField(blank=True, null=True)),
                ('is_built_after_1960', models.BooleanField(blank=True, null=True)),
                ('comment', models.TextField(blank=True, null=True)),
                ('current_home', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='application.CurrentHome')),
            ],
        ),
        migrations.CreateModel(
            name='Comparable',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('mls', models.CharField(choices=[('GA_FMLS', 'GA_FMLS'), ('GA_MLS', 'GA_MLS'), ('TX_SABOR', 'TX_SABOR'), ('TX_HAR', 'TX_HAR'), ('TX_ACTRIS', 'TX_ACTRIS'), ('TX_NTREIS', 'TX_NTREIS'), ('CO_Metrolist', 'CO_Metrolist'), ('CO_IRES', 'CO_IRES')], max_length=50)),
                ('listing_id', models.CharField(max_length=20)),
                ('comparable_type', models.CharField(choices=[('Primary', 'Primary'), ('Secondary', 'Secondary')], max_length=50)),
                ('comment', models.TextField(blank=True, null=True)),
                ('market_value_analysis', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='application.MarketValueAnalysis')),
            ],
        ),
    ]
