# Generated by Django 2.2 on 2019-05-21 15:02

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0011_auto_20190520_2104'),
    ]

    operations = [
        migrations.CreateModel(
            name='CurrentHomeImage',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('url', models.TextField()),
                ('label', models.TextField()),
                ('current_home', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='application.CurrentHome')),
            ],
        ),
    ]
