# Generated by Django 2.2 on 2019-05-21 15:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0012_currenthomeimage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='currenthomeimage',
            name='url',
            field=models.TextField(unique=True),
        ),
    ]
