# Generated by Django 2.2 on 2019-05-21 19:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0014_auto_20190521_1603'),
    ]

    operations = [
        migrations.AlterField(
            model_name='application',
            name='stage',
            field=models.CharField(choices=[('draft', 'draft'), ('complete', 'complete'), ('market value submitted', 'market value submitted')], max_length=50),
        ),
    ]
