# Generated by Django 2.2 on 2019-05-22 06:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0015_auto_20190521_1930'),
        ('application', '0010_auto_20190521_0614'),
    ]

    operations = [
    ]
