# Generated by Django 2.2 on 2019-05-24 07:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0016_merge_20190523_1310'),
        ('application', '0017_application_offer_property_address'),
    ]

    operations = [
    ]
