# Generated by Django 2.2 on 2019-05-30 19:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0018_merge_20190524_0720'),
    ]

    operations = [
        migrations.AddField(
            model_name='realestateagent',
            name='company',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
