# Generated by Django 2.2 on 2019-06-04 18:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0020_auto_20190531_1445'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='application',
            name='hubspot_error_retry_count',
        ),
        migrations.RemoveField(
            model_name='application',
            name='sf_error_retry_count',
        ),
    ]
