# Generated by Django 2.2 on 2019-06-18 07:24

import application.models.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0022_auto_20190611_0656'),
    ]

    operations = [
        migrations.AddField(
            model_name='currenthomeimage',
            name='status',
            field=models.CharField(choices=[('pending', 'pending'), ('uploaded', 'uploaded')], default=application.models.models.CurrentHomeImageStatus('pending'), max_length=50),
        ),
    ]
