# Generated by Django 2.2 on 2019-06-19 09:48

import application.models.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0023_currenthomeimage_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='currenthomeimage',
            name='label',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='currenthomeimage',
            name='status',
            field=models.CharField(choices=[('pending', 'pending'), ('uploaded', 'uploaded'), ('labeled', 'labeled')], default=application.models.models.CurrentHomeImageStatus('pending'), max_length=50),
        ),
    ]
