# Generated by Django 2.2 on 2019-06-20 05:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0024_auto_20190619_0948'),
        ('application', '0025_auto_20190618_1414'),
    ]

    operations = [
    ]
