# Generated by Django 2.2 on 2019-06-17 09:21

import application.models.models
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0025_auto_20190618_1414'),
    ]

    operations = [
        migrations.CreateModel(
            name='PreApproval',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True, null=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('decision_date', models.DateTimeField(blank=True, null=True)),
                ('expiration_date', models.DateTimeField(blank=True, null=True)),
                ('mortgage_amount', models.IntegerField(blank=True, null=True)),
                ('down_payment', models.IntegerField(blank=True, null=True)),
                ('reason_for_denial', models.CharField(blank=True, max_length=255, null=True)),
                ('property_type', models.CharField(blank=True, choices=[('Single Family Home', 'Single Family Home'), ('Condo', 'Condo'), (
                    'Co-op', 'Co-op'), ('Planned Unit Developement(PUD)', 'Planned Unit Developement(PUD)'), ('2-4 Units', '2-4 Units')], max_length=100, null=True)),
                ('request_date', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(choices=[('New', 'New'), ('In-Process', 'In-Process'), ('Approved', 'Approved'),
                                                     ('Denied', 'Denied'), ('Open', 'Open')], default='New', max_length=50)),
                ('application', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pre_approvals', to='application.Application')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
