# Generated by Django 2.2 on 2019-06-19 12:48

import application.models.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0026_preapproval'),
    ]

    operations = [
        migrations.AlterField(
            model_name='preapproval',
            name='property_type',
            field=models.CharField(blank=True, choices=[('Single Family Home', 'Single Family Home'), ('Condo', 'Condo'), ('Co-op', 'Co-op'), ('2-4 Units', '2-4 Units')], max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='preapproval',
            name='status',
            field=models.CharField(choices=[('New', 'New'), ('In-Process', 'In-Process'), ('Approved', 'Approved'), ('Denied', 'Denied')], default='New', max_length=50),
        ),
    ]
