# Generated by Django 2.2 on 2019-06-20 13:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0026_merge_20190620_0527'),
        ('application', '0028_auto_20190620_1239'),
    ]

    operations = [
    ]
