# Generated by Django 2.2 on 2019-06-24 14:06
from django.apps import apps
from django.db import migrations


def remove_duplicates_and_nones(current_homes, schema_editor):
    return
    # CurrentHome = apps.get_model("application", "CurrentHome")
    # for home in CurrentHome.objects.all():
    #     try:
    #         home.attributes['walls_and_flooring']['flooring_types'] = \
    #             list(filter(None.__ne__, set(home.attributes['walls_and_flooring']['flooring_types'])))
    #         home.attributes.get('walls_and_flooring', {}).get('flooring_types', []).remove('')
    #         home.save()
    #     except (TypeError, KeyError, ValueError):
    #         pass


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0029_merge_20190620_1316'),
    ]

    operations = [
        migrations.RunPython(remove_duplicates_and_nones, elidable=True)
    ]
