# Generated by Django 2.2 on 2019-06-26 05:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0030_auto_20190624_1406'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mortgagelender',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name='mortgagelender',
            name='name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='mortgagelender',
            name='phone',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='realestateagent',
            name='name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
