# Generated by Django 2.2 on 2019-06-28 05:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0032_auto_20190627_0610'),
    ]

    operations = [
        migrations.AlterField(
            model_name='builder',
            name='address',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='application.Address'),
        ),
        migrations.AlterField(
            model_name='builder',
            name='name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
