# Generated by Django 2.2 on 2019-07-02 10:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0034_auto_20190702_1041'),
    ]

    operations = [
        migrations.AlterField(
            model_name='marketvalueopinioncomment',
            name='comment',
            field=models.TextField(default=None, max_length=140),
            preserve_default=False,
        ),
    ]
