# Generated by Django 2.2 on 2019-07-03 06:44

import application.models.models
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0036_auto_20190702_1115'),
    ]

    operations = [
        migrations.CreateModel(
            name='MarketValueReport',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True, null=True)),
                ('name', models.CharField(blank=True, choices=[('House Canary', 'House Canary')], default=application.models.models.MarketValueReportName('House Canary'), max_length=50, null=True)),
                ('link', models.URLField(blank=True, null=True)),
                ('market_valuation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='avm', to='application.MarketValuation')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
