# Generated by Django 2.2 on 2019-07-15 10:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0038_auto_20190704_0950'),
    ]

    operations = [
        migrations.AlterField(
            model_name='application',
            name='stage',
            field=models.CharField(choices=[('draft', 'draft'), ('complete', 'complete'), ('qualified application', 'qualified application'), ('local valuation', 'local valuation'), ('internal valuation', 'internal valuation'), ('mortgage approval', 'mortgage approval'), ('approved', 'approved'), ('denied', 'denied'), ('max offer requested', 'max offer requested'), ('offer negotiations', 'offer negotiations'), ('option period', 'option period'), ('post option', 'post option'), ('homeward purchase', 'homeward purchase'), ('customer purchase', 'customer purchase'), ('cancelled contract', 'cancelled contract'), ('TRASH', 'TRASH')], max_length=50),
        ),
    ]
