# Generated by Django 2.2 on 2019-08-05 11:20

from django.conf import settings
from django.db import migrations

# from application.tasks import backfill_leads

def backfill_leads_migration(apps, schema_editor):
    pass

class Migration(migrations.Migration):

    dependencies = [
        ('application', '0042_auto_20190730_1847'),
    ]

    operations = [] + [
        migrations.RunPython(backfill_leads_migration)
    ] if getattr(settings, 'APP_ENV', 'test') not in ['local', 'test'] else []
