# Generated by Django 2.2 on 2019-08-08 09:36

from django.conf import settings
from django.db import migrations


def set_start_date_migration(apps, schema_editor):
    pass
    # One time running the function. 
    # set_startdata_backfill_leads(bucket='homeward-test', key='CSV/HW crm backfill - hw backfill import - 08022019 .csv')     #pragma: no cover

class Migration(migrations.Migration):

    dependencies = [
        ('application', '0043_auto_20190805_1120'),
    ]

    operations = [] + [
        migrations.RunPython(set_start_date_migration)
    ] if getattr(settings, 'APP_ENV', 'test') not in ['local', 'test'] else []
