# Generated by Django 2.2 on 2019-07-31 09:11

import application.models.models
from django.db import migrations, models
import django.db.models.deletion
import uuid

from application.models.task_progress import TaskProgress


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0043_auto_20190805_1120'),
    ]

    operations = [
        migrations.CreateModel(
            name='TaskStatus',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True, null=True)),
                ('task', models.CharField(choices=[('existing_property', 'existing_property'), ('real_estate_agent', 'real_estate_agent'), ('mortgage_preapproval', 'mortgage_preapproval'), ('buying_situation', 'buying_situation')], max_length=50)),
                ('status', models.CharField(choices=[('Not started', 'Not started'), ('In progress', 'In progress'), ('Completed', 'Completed')], default=TaskProgress('Not started'), max_length=50)),
                ('application', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='task_status', to='application.Application')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
