# Generated by Django 2.2 on 2019-08-09 13:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0044_auto_20190808_0936'),
    ]

    operations = [
        migrations.AddField(
            model_name='application',
            name='self_reported_referral_source',
            field=models.CharField(blank=True, choices=[('My agent', 'My agent'), ('My loan officer', 'My loan officer'), ('My home builder', 'My home builder'), ('A friend', 'A friend'), ('Online ad', 'Online ad'), ('Radio', 'Radio'), ('Sign in yard', 'Sign in yard'), ('Other', 'Other'), ('None', 'None')], max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='application',
            name='self_reported_referral_source_detail',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
