# Generated by Django 2.2 on 2019-08-09 09:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0044_taskstatus'),
    ]

    operations = [
        migrations.AlterField(
            model_name='currenthomeimage',
            name='label',
            field=models.TextField(choices=[('kitchen', 'kitchen'), ('living_room', 'living_room'), ('master_bath', 'master_bath'), ('front_exterior', 'front_exterior'), ('all_other_rooms', 'all_other_rooms')], null=True),
        ),
    ]
