# Generated by Django 2.2 on 2019-08-09 10:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0044_auto_20190808_0936'),
        ('application', '0045_auto_20190809_0927'),
    ]

    operations = [
    ]
