# Generated by Django 2.2 on 2019-08-09 15:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0045_auto_20190809_1328'),
    ]

    operations = [
        migrations.AlterField(
            model_name='application',
            name='self_reported_referral_source',
            field=models.CharField(blank=True, choices=[('my_agent', 'my_agent'), ('my_loan_officer', 'my_loan_officer'), ('my_home_builder', 'my_home_builder'), ('a_friend', 'a_friend'), ('online_ad', 'online_ad'), ('radio', 'radio'), ('sign_in_yard', 'sign_in_yard'), ('other', 'other')], max_length=255, null=True),
        ),
    ]
