# Generated by Django 2.2 on 2019-08-12 05:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0046_merge_20190809_1000'),
        ('application', '0046_auto_20190809_1522'),
    ]

    operations = [
    ]
