# Generated by Django 2.2 on 2019-08-20 06:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0048_auto_20190815_2007'),
    ]

    operations = [
        migrations.AlterField(
            model_name='application',
            name='stage',
            field=models.CharField(choices=[('draft', 'draft'), ('complete', 'complete'), ('qualified application', 'qualified application'), ('floor price valuation', 'floor price valuation'), ('mortgage approval', 'mortgage approval'), ('approved', 'approved'), ('denied', 'denied'), ('max offer requested', 'max offer requested'), ('offer negotiations', 'offer negotiations'), ('option period', 'option period'), ('post option', 'post option'), ('homeward purchase', 'homeward purchase'), ('customer purchase', 'customer purchase'), ('cancelled contract', 'cancelled contract'), ('trash', 'trash')], max_length=50),
        ),
    ]
