# Generated by Django 2.2 on 2019-08-20 06:29

from django.db import migrations
from application.models.models import (ApplicationStage, NoteType)

def merge_valuation_stages(apps, schema_editor):
    Application = apps.get_model('application', 'application')
    Application.objects.filter(stage__in=['local valuation', 'internal valuation']).update(stage=ApplicationStage.FLOOR_PRICE_REQUESTED)

def reverse_merge_valuation_stage(apps, schema_editor):
    Application = apps.get_model('application', 'application')
    Application.objects.filter(stage=ApplicationStage.FLOOR_PRICE_REQUESTED).update(stage='local valuation')

def update_note_title(apps, schema_editor):
    Note = apps.get_model('application', 'note')
    notes = Note.objects.filter(type=NoteType.APPLICATION_STAGE)
    for note in notes:
        note.title = note.title.replace('Application stage update: ', '')
        note.save()

class Migration(migrations.Migration):

    dependencies = [
        ('application', '0049_auto_20190820_0627'),
    ]

    operations = [
        migrations.RunPython(merge_valuation_stages, reverse_merge_valuation_stage, elidable=True),
        migrations.RunPython(update_note_title, elidable=True)
    ]
