# Generated by Django 2.2 on 2019-09-03 23:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0050_auto_20190820_0629'),
    ]

    operations = [
        migrations.AlterField(
            model_name='application',
            name='stage',
            field=models.CharField(choices=[('draft', 'draft'), ('incomplete', 'incomplete'), ('complete', 'complete'), ('qualified application', 'qualified application'), ('floor price valuation', 'floor price valuation'), ('mortgage approval', 'mortgage approval'), ('approved', 'approved'), ('denied', 'denied'), ('max offer requested', 'max offer requested'), ('offer requested', 'offer requested'), ('offer negotiations', 'offer negotiations'), ('offer submitted', 'offer submitted'), ('option period', 'option period'), ('post option', 'post option'), ('homeward purchase', 'homeward purchase'), ('customer purchase', 'customer purchase'), ('customer closed', 'customer closed'), ('cancelled contract', 'cancelled contract'), ('trash', 'trash')], max_length=50),
        ),
    ]