# Generated by Django 2.2 on 2019-09-03 23:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0052_auto_20190903_2302'),
    ]

    operations = [
        migrations.AlterField(
            model_name='application',
            name='stage',
            field=models.CharField(choices=[('incomplete', 'incomplete'), ('complete', 'complete'), ('qualified application', 'qualified application'), ('floor price valuation', 'floor price valuation'), ('approved', 'approved'), ('denied', 'denied'), ('offer requested', 'offer requested'), ('offer submitted', 'offer submitted'), ('option period', 'option period'), ('post option', 'post option'), ('homeward purchase', 'homeward purchase'), ('customer closed', 'customer closed'), ('cancelled contract', 'cancelled contract'), ('trash', 'trash')], max_length=50),
        ),
    ]
