# Generated by Django 2.2 on 2019-09-06 14:56

from django.db import migrations
from django.db.migrations import RunPython
from django.conf import settings
from simple_salesforce import Salesforce


def update_addresses_in_salesforce(apps, schema_editor):
    if not settings.NEW_SALESFORCE:
        return

    Application = apps.get_model('application', 'Application')
    applications_in_salesforce_with_home = Application.objects.filter(new_salesforce__isnull=False,
                                                                      current_home__isnull=False)
    salesforce = Salesforce(**settings.NEW_SALESFORCE)
    sf_model = getattr(salesforce, "Account")

    for application in applications_in_salesforce_with_home:
        address = application.current_home.address
        address_info = {
            'BillingStreet': address.street if address.street else '',
            'BillingCity': address.city if address.city else '',
            'BillingState': address.state if address.state else '',
            'BillingPostalCode': address.zip if address.zip else ''
        }
        sf_model.update(application.new_salesforce, address_info)


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0053_auto_20190903_2304'),
    ]

    operations = [
        migrations.RunPython(update_addresses_in_salesforce, RunPython.noop, elidable=True)
    ]
