# Generated by Django 2.2 on 2019-09-12 06:16

import application.models.models
from django.db import migrations, models

from application.models.task_progress import TaskProgress


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0054_auto_20190906_1456'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='taskstatus',
            options={'ordering': ('created_at',)},
        ),
        migrations.AlterField(
            model_name='taskstatus',
            name='status',
            field=models.CharField(choices=[('Not started', 'Not started'), ('In progress', 'In progress'), ('Completed', 'Completed'), ('Approved', 'Approved'), ('Denied', 'Denied')], default=TaskProgress('Not started'), max_length=50),
        ),
        migrations.AlterField(
            model_name='taskstatus',
            name='task',
            field=models.CharField(choices=[('existing_property', 'existing_property'), ('real_estate_agent', 'real_estate_agent'), ('mortgage_preapproval', 'mortgage_preapproval'), ('buying_situation', 'buying_situation'), ('floor_price_calculated', 'floor_price_calculated')], max_length=50),
        ),
    ]
