# Generated by Django 2.2 on 2019-09-12 11:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0055_auto_20190912_0616'),
    ]

    operations = [
        migrations.AlterField(
            model_name='taskstatus',
            name='task',
            field=models.CharField(choices=[('existing_property', 'existing_property'), ('real_estate_agent', 'real_estate_agent'), ('mortgage_preapproval', 'mortgage_preapproval'), ('buying_situation', 'buying_situation'), ('floor_price_calculated', 'floor_price_calculated'), ('homeward_approval', 'homeward_approval')], max_length=50),
        ),
    ]
