# Generated by Django 2.2 on 2019-09-10 22:07

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0056_auto_20190912_1111'),
    ]

    operations = [
        migrations.CreateModel(
            name='StageHistory',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True, null=True)),
                ('previous_stage', models.CharField(choices=[('incomplete', 'incomplete'), ('complete', 'complete'), ('qualified application', 'qualified application'), ('floor price valuation', 'floor price valuation'), ('approved', 'approved'), ('denied', 'denied'), ('offer requested', 'offer requested'), ('offer submitted', 'offer submitted'), ('option period', 'option period'), ('post option', 'post option'), ('homeward purchase', 'homeward purchase'), ('customer closed', 'customer closed'), ('cancelled contract', 'cancelled contract'), ('trash', 'trash')], max_length=50)),
                ('new_stage', models.CharField(choices=[('incomplete', 'incomplete'), ('complete', 'complete'), ('qualified application', 'qualified application'), ('floor price valuation', 'floor price valuation'), ('approved', 'approved'), ('denied', 'denied'), ('offer requested', 'offer requested'), ('offer submitted', 'offer submitted'), ('option period', 'option period'), ('post option', 'post option'), ('homeward purchase', 'homeward purchase'), ('customer closed', 'customer closed'), ('cancelled contract', 'cancelled contract'), ('trash', 'trash')], max_length=50)),
                ('application', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='application.Application')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
