# Generated by Django 2.2 on 2019-09-16 20:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0057_stagehistory'),
    ]

    operations = [
        migrations.AddField(
            model_name='application',
            name='home_buying_location',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='home_buying_location', to='application.Address'),
        ),
        migrations.AlterField(
            model_name='application',
            name='offer_property_address',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='offer_property_address', to='application.Address'),
        ),
    ]
