# Generated by Django 2.2 on 2019-09-19 15:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0060_currenthomeimage_created_by'),
    ]

    operations = [
        migrations.AddField(
            model_name='application',
            name='reason_for_trash',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
