# Generated by Django 2.2 on 2019-09-19 19:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0061_application_reason_for_trash'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='application',
            name='salesforce',
        ),
    ]
