# Generated by Django 2.2 on 2019-09-25 16:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0062_remove_application_salesforce'),
    ]

    operations = [
        migrations.RenameField(
            model_name='builder',
            old_name='name',
            new_name='company_name',
        ),
        migrations.AddField(
            model_name='application',
            name='internal_referral',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='builder',
            name='representative_email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='builder',
            name='representative_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='builder',
            name='representative_phone',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
