# Generated by Django 2.2 on 2019-10-09 16:45

from django.db import migrations
from django.db.migrations import RunPython


def migrate_application_stages(apps, schema_editor):
    Application = apps.get_model('application', 'Application')
    Application.objects.filter(stage='floor price valuation').update(stage='floor price requested')


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0063_auto_20190925_1616'),
    ]

    operations = [
        migrations.RunPython(migrate_application_stages, RunPython.noop, elidable=True)
    ]
