# Generated by Django 2.2 on 2019-11-07 15:02

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0065_auto_20191011_1554'),
    ]

    operations = [
        migrations.CreateModel(
            name='RealEstateLead',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True, null=True)),
                ('needs_buying_agent', models.BooleanField()),
                ('needs_listing_agent', models.BooleanField()),
                ('home_buying_stage', models.CharField(choices=[('researching online', 'researching online'), ('viewing listings in person', 'viewing listings in person'), ('making an offer', 'making an offer'), ('working with a builder', 'working with a builder')], max_length=50)),
                ('address', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='market_location', to='application.Address')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='application.Customer')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
