# Generated by Django 2.2 on 2019-12-06 16:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0067_auto_20191205_2244'),
    ]

    operations = [
        migrations.AlterField(
            model_name='currenthomeimage',
            name='label',
            field=models.TextField(blank=True, choices=[('kitchen', 'kitchen'), ('living_room', 'living_room'), ('master_bath', 'master_bath'), ('front_exterior', 'front_exterior'), ('all_other_rooms', 'all_other_rooms')], null=True),
        ),
        migrations.AlterField(
            model_name='taskstatus',
            name='task',
            field=models.CharField(choices=[('existing_property', 'existing_property'), ('real_estate_agent', 'real_estate_agent'), ('mortgage_preapproval', 'mortgage_preapproval'), ('buying_situation', 'buying_situation'), ('floor_price_calculated', 'floor_price_calculated'), ('homeward_approval', 'homeward_approval'), ('photo_upload', 'photo_upload')], max_length=50),
        ),
    ]
