# Generated by Django 2.2 on 2019-12-18 22:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0068_auto_20191206_1658'),
    ]

    operations = [
        migrations.AlterField(
            model_name='application',
            name='move_in',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
