# Generated by Django 2.2 on 2019-12-23 16:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0069_auto_20191218_2244'),
    ]

    operations = [
        migrations.AddField(
            model_name='application',
            name='buying_agent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='buying_agent_applications', to='application.RealEstateAgent'),
        ),
        migrations.AddField(
            model_name='application',
            name='listing_agent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='listing_agent_applications', to='application.RealEstateAgent'),
        ),
        migrations.AlterField(
            model_name='application',
            name='move_in',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
