# Generated by Django 2.2 on 2019-12-23 16:57

from django.db import migrations
from django.db.migrations import RunPython


def convert_agent_to_listing_and_buying_agent(apps, schema_editor):
    Application = apps.get_model("application", "Application")
    for app in Application.objects.filter(real_estate_agent__isnull=False):
        app.listing_agent = app.real_estate_agent
        app.buying_agent = app.real_estate_agent
        app.save()


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0070_auto_20191223_1655'),
    ]

    operations = [
        migrations.RunPython(convert_agent_to_listing_and_buying_agent, RunPython.noop, elidable=True)
    ]
