# Generated by Django 2.2 on 2020-01-22 20:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0074_auto_20200122_1357'),
    ]

    operations = [
        migrations.AddField(
            model_name='application',
            name='needs_buying_agent',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='application',
            name='needs_listing_agent',
            field=models.BooleanField(blank=True, null=True),
        ),
    ]
