# Generated by Django 2.2 on 2020-01-23 16:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0075_auto_20200122_2005'),
        ('application', '0071_auto_20191223_1657'),
    ]

    operations = [
    ]
