# Generated by Django 2.2 on 2020-01-23 16:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0076_merge_20200123_1614'),
    ]

    operations = [
        migrations.AddField(
            model_name='application',
            name='has_consented_to_receive_electronic_documents',
            field=models.BooleanField(default=False),
        ),
    ]
