# Generated by Django 2.2 on 2020-01-23 19:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0077_application_has_consented_to_receive_electronic_documents'),
    ]

    operations = [
        migrations.AddField(
            model_name='realestateagent',
            name='self_reported_referral_source',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='realestateagent',
            name='self_reported_referral_source_detail',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
