# Generated by Django 2.2 on 2020-01-28 22:42

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0079_auto_20200123_2005'),
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True, null=True)),
                ('name', models.CharField(max_length=50)),
                ('category', models.CharField(choices=[('existing_property', 'existing_property'), ('real_estate_agent', 'real_estate_agent'), ('mortgage_preapproval', 'mortgage_preapproval'), ('buying_situation', 'buying_situation'), ('floor_price_calculated', 'floor_price_calculated'), ('homeward_approval', 'homeward_approval'), ('photo_upload', 'photo_upload')], max_length=50)),
                ('start_date', models.DateField(auto_now=True, null=True)),
                ('end_date', models.DateField(blank=True, null=True)),
                ('active', models.BooleanField(default=False)),
                ('state', models.CharField(blank=True, max_length=50, null=True)),
                ('partner', models.CharField(max_length=50)),
                ('options', django.contrib.postgres.fields.jsonb.JSONField(blank=True, default=dict, null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.RenameField(
            model_name='taskstatus',
            old_name='task',
            new_name='category',
        ),
    ]
