# Generated by Django 2.2 on 2020-01-28 22:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0080_auto_20200128_2242'),
    ]

    operations = [
        migrations.AddField(
            model_name='taskstatus',
            name='task',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='application.Task'),
        ),
    ]
