# Generated by Django 2.2 on 2020-01-28 19:24

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0082_acknowledgeabledocument'),
    ]

    operations = [
        migrations.CreateModel(
            name='Acknowledgement',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True, null=True)),
                ('ip_address', models.CharField(max_length=50)),
                ('is_acknowledged', models.BooleanField()),
                ('application', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='application.Application')),
                ('document', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='application.AcknowledgeableDocument')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
