# Generated by Django 2.2 on 2020-01-28 23:00

from django.db import migrations
from django.db.migrations import RunPython

from application.models.task_category import TaskCategory


def create_new_tasks(apps, schema_editor):
    Task = apps.get_model("application", "Task")

    for category in TaskCategory:
        Task.objects.create(name=category.value, category=category.value, active=True)


def migrate_existing_tasks(apps, schema_editor):
    TaskStatus = apps.get_model("application", "TaskStatus")
    Task = apps.get_model("application", "Task")

    for status in TaskStatus.objects.all():
        status.task_obj = Task.objects.get(name=status.category)
        status.save()


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0083_acknowledgement'),
    ]

    operations = [
        migrations.RunPython(create_new_tasks, RunPython.noop),
        migrations.RunPython(migrate_existing_tasks, RunPython.noop)
    ]
