# Generated by Django 2.2 on 2020-01-29 21:59

from django.db import migrations
from django.db.migrations import RunPython

from application.models.task_category import TaskCategory


def assign_tasks_order(apps, schema_editor):
    Task = apps.get_model("application", "Task")
    Task.objects.filter(name=TaskCategory.BUYING_SITUATION).update(order=0)
    Task.objects.filter(name=TaskCategory.REAL_ESTATE_AGENT).update(order=1)
    Task.objects.filter(name=TaskCategory.EXISTING_PROPERTY).update(order=2)
    Task.objects.filter(name=TaskCategory.PHOTO_UPLOAD).update(order=3)
    Task.objects.filter(name='mortgage_preapproval').update(order=5)


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0085_auto_20200129_2159'),
    ]

    operations = [
        migrations.RunPython(assign_tasks_order, RunPython.noop),
    ]
