# Generated by Django 2.2 on 2020-01-29 22:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0086_auto_20200129_2159'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='category',
            field=models.CharField(choices=[('existing_property', 'existing_property'), ('real_estate_agent', 'real_estate_agent'), ('mortgage_preapproval', 'mortgage_preapproval'), ('buying_situation', 'buying_situation'), ('photo_upload', 'photo_upload'), ('abad', 'abad')], max_length=50),
        ),
        migrations.AlterField(
            model_name='taskstatus',
            name='category',
            field=models.CharField(choices=[('existing_property', 'existing_property'), ('real_estate_agent', 'real_estate_agent'), ('mortgage_preapproval', 'mortgage_preapproval'), ('buying_situation', 'buying_situation'), ('photo_upload', 'photo_upload'), ('abad', 'abad')], max_length=50),
        ),
    ]
