# Generated by Django 2.2 on 2020-01-31 22:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0087_auto_20200129_2203'),
    ]

    operations = [
        migrations.RenameField(
            model_name='taskstatus',
            old_name='task',
            new_name='task_obj',
        ),
    ]
