# Generated by Django 2.2 on 2020-01-31 22:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0088_auto_20200131_2220'),
    ]

    operations = [
        migrations.RenameField(
            model_name='taskstatus',
            old_name='category',
            new_name='task',
        ),
    ]
