# Generated by Django 2.2 on 2020-02-04 22:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0091_abad_rename'),
    ]

    operations = [
        migrations.AlterField(
            model_name='acknowledgement',
            name='ip_address',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='acknowledgement',
            name='is_acknowledged',
            field=models.BooleanField(default=False),
        ),
    ]
