# Generated by Django 2.2 on 2020-02-05 21:54
from django.db.migrations import RunPython

from django.db import migrations

def add_texas_disclosure(apps, schema_editor):
    Disclosure = apps.get_model("application", "Disclosure")

    name = "homeward title (texas)"
    doc_url = 'https://storage.googleapis.com/acknowledgeable_documents/texas-homeward-title.pdf'
    Disclosure.objects.create(name=name, document_url=doc_url)

class Migration(migrations.Migration):

    dependencies = [
        ('application', '0094_auto_20200205_1537'),
    ]

    operations = [
        migrations.RunPython(add_texas_disclosure, RunPython.noop),
    ]
