# Generated by Django 2.2 on 2020-02-05 22:48

from django.db import migrations
from django.db.migrations import RunPython

from application.models.task_category import TaskCategory
from application.models.task_name import TaskName


def change_lender_task_and_add_mortgage_task(apps, schema_editor):
    Task = apps.get_model("application", "Task")

    lender_task, _ = Task.objects.get_or_create(name='mortgage_preapproval')
    lender_task.name = TaskName.MY_LENDER_BETTER
    lender_task.category = TaskCategory.LENDER
    lender_task.active = True
    lender_task.options = '{\
      "icon": "/tasks/shield.png",\
      "route": "/tasks/lender_better_variation",\
      "time": "3 min",\
      "direct": true\
    }'
    lender_task.save()

    Task.objects.create(name=TaskName.MY_LENDER, category=TaskCategory.LENDER, order=5, active=True, options='{\
      "icon": "/tasks/shield.png",\
      "route": "/tasks/lender_variation",\
      "time": "3 min",\
      "direct": true\
    }')

    Task.objects.create(name=TaskName.COLORADO_MORTGAGE, category=TaskCategory.HOMEWARD_MORTGAGE, order=6,
                        active=False, state='co', options='{"title": "Verified Pre-Approval","description":"Get a verified mortgage pre-approval to use Homeward\'s Cash Offer","route": "mortgage","stepTitle":"Get your verified mortgage pre-approval","stepDescription":"Complete a verified, full pre-approval with Homeward Mortgage.","stepActionLabel": "Get Verified"}')


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0095_auto_20200205_2054'),
    ]

    operations = [
        migrations.RunPython(change_lender_task_and_add_mortgage_task, RunPython.noop),
    ]
