# Generated by Django 2.2 on 2020-02-06 19:00

from django.db import migrations
from django.db.migrations import RunPython

from application.models.task_category import TaskCategory
from application.models.task_name import TaskName


def add_dependency_to_mortgage_task(apps, schema_editor):
    TaskDependency = apps.get_model("application", "TaskDependency")
    Task = apps.get_model("application", "Task")

    mortgage_task = Task.objects.get(name=TaskName.COLORADO_MORTGAGE)
    disclosure_task = Task.objects.get(category=TaskCategory.DISCLOSURES)
    TaskDependency.objects.create(parent_task=mortgage_task, depends_on=disclosure_task)


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0097_auto_20200206_1548'),
    ]

    operations = [
        migrations.RunPython(add_dependency_to_mortgage_task, RunPython.noop),
    ]
