# Generated by Django 2.2 on 2020-02-06 21:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0098_auto_20200206_1900'),
    ]

    operations = [
        migrations.AddField(
            model_name='application',
            name='needs_lender',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='acknowledgement',
            name='application',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='acknowledgements', to='application.Application'),
        ),
        migrations.AlterField(
            model_name='task',
            name='category',
            field=models.CharField(choices=[('existing_property', 'existing_property'), ('real_estate_agent', 'real_estate_agent'), ('homeward_mortgage', 'homeward_mortgage'), ('lender', 'lender'), ('buying_situation', 'buying_situation'), ('photo_upload', 'photo_upload'), ('disclosures', 'disclosures')], max_length=50),
        ),
        migrations.AlterField(
            model_name='task',
            name='name',
            field=models.CharField(choices=[('existing_property', 'existing_property'), ('real_estate_agent', 'real_estate_agent'), ('my_lender', 'my_lender'), ('my_lender_better', 'my_lender_better'), ('buying_situation', 'buying_situation'), ('photo_upload', 'photo_upload'), ('disclosures', 'disclosures'), ('co_mortgage', 'co_mortgage')], max_length=50, unique=True),
        ),
    ]
