# Generated by Django 2.2 on 2020-02-06 21:21

from django.db import migrations
from django.db.migrations import RunPython

def update_task_options(apps, schema_editor):
    Task = apps.get_model("application", "Task")

    updates = {
        "photo_upload": {
            "icon": "/tasks/photo.png",
            "time": "5 min",
            "route": "/tasks/current_home_photos_variation",
            "title": "Upload photos",
            "direct": True,
            "stepTitle": "Upload photos of your existing property",
            "description": "Upload photos of your existing home",
            "stepActionLabel": "Upload photos",
            "stepDescription": "More photos mean a more accurate valuation. Don't receive a low Floor Price because of too few photos."
        },
        "my_lender_better": {
            "icon": "/tasks/shield.png",
            "time": "1 min",
            "route": "/tasks/lender_better_variation",
            "title": "Mortgage pre-approval",
            "direct": True,
            "stepTitle": "Complete your mortgage pre-approval",
            "description": "Tell us about your current mortgage lender",
            "stepActionLabel": "Complete your pre-approval",
            "stepDescription": "Congratulations! You're one step away from getting approved to make a Homeward all cash offer. Enter your lender and mortgage pre-approval information to complete your application."
        },
        "disclosures": {
            "icon": "/tasks/disclosures.png",
            "time": "2 min",
            "route": "/disclosures",
            "title": "Review electronic documents",
            "direct": False,
            "stepTitle": "Review electronic documents",
            "description": "Take a moment to review a few important electronic documents",
            "stepActionLabel": "Review & acknowledge documents",
            "stepDescription": "Take a moment to review a few important electronic documents."
        },
        "my_lender": {
            "icon": "/tasks/shield.png",
            "time": "1 min",
            "route": "/tasks/lender_variation",
            "title": "Your lender",
            "direct": True,
            "stepTitle": "Tell us about your mortgage lender",
            "description": "If you have one, tell us about your current mortgage lender",
            "stepActionLabel": "About your lender",
            "stepDescription": "Tell us about your mortgage lender so we can coordinate directly with them to save you time."
        },
        "co_mortgage": {
            "icon": "/tasks/mortgage.png",
            "time": "20 min",
            "route": "/tasks/hw_mortgage_variation",
            "title": "Verify mortgage eligibility",
            "direct": True,
            "stepTitle": "Get your verified mortgage pre-approval",
            "description": "Get a verified mortgage pre-approval to use Homeward's Cash Offer",
            "stepActionLabel": "Get Verified",
            "stepDescription": "Complete a verified, full pre-approval with Homeward Mortgage."
        },
        "buying_situation": {
            "icon": "/tasks/computer.png",
            "time": "4 min",
            "route": "/tasks/situation_variation",
            "title": "Your buying situation",
            "direct": False,
            "description": "Tell us about you and your current home buying situation"
        },
        "real_estate_agent": {
            "icon": "/tasks/badge.png",
            "time": "1 min",
            "route": "/tasks/agents_variation",
            "title": "Your real estate agent",
            "direct": True,
            "stepTitle": "Tell us about your real estate agent",
            "description": "If you have one, tell us about your real estate agent",
            "stepActionLabel": "About your agent",
            "stepDescription": "Tell us about your real estate agent so we can coordinate directly with them to save you time."
        },
        "existing_property": {
            "icon": "/tasks/home.png",
            "time": "10 min",
            "route": "/tasks/current_home_variation",
            "title": "Your existing property",
            "direct": False,
            "stepTitle": "Tell us about your existing property",
            "description": "Tell us more about $property_address",
            "stepActionLabel": "About your existing property",
            "stepDescription": "Please tell us about the home you're selling so we can calculate your home equity and get you approved to make a Homeward all cash offer."
        }
    }


    for task in Task.objects.all():
        task.options = updates.get(task.name, None)
        task.save()

class Migration(migrations.Migration):

    dependencies = [
        ('application', '0099_auto_20200206_2158'),
    ]

    operations = [
        migrations.RunPython(update_task_options, RunPython.noop),
    ]
