# Generated by Django 2.2 on 2020-02-07 22:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0100_auto_20200207_1628'),
    ]

    operations = [
        migrations.AddField(
            model_name='disclosure',
            name='buying_state',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='disclosure',
            name='selling_state',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
