# Generated by Django 2.2 on 2020-02-07 22:40

from django.db.migrations import RunPython

from django.db import migrations

def add_states_to_disclosures(apps, schema_editor):
    Disclosure = apps.get_model("application", "Disclosure")

    name = 'homeward mortgage (colorado)'
    doc_url = 'https://storage.googleapis.com/acknowledgeable_documents/Colorado%20Mortgage%20Disclosure.pdf'
    Disclosure.objects.create(name=name, document_url=doc_url, buying_state='co', selling_state=None)

    tx = Disclosure.objects.get(name='homeward title (texas)')

    tx.buying_state = 'tx'
    tx.selling_state = 'tx'
    tx.save()

class Migration(migrations.Migration):
    dependencies = [
        ('application', '0101_auto_20200207_2236'),
    ]

    operations = [
        migrations.RunPython(add_states_to_disclosures, RunPython.noop),
    ]
