# Generated by Django 2.2 on 2020-02-11 14:42

import application.models.task_progress
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0103_task_is_editable'),
    ]

    operations = [
        migrations.AddField(
            model_name='application',
            name='blend_status',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='application',
            name='stage',
            field=models.CharField(choices=[('incomplete', 'incomplete'), ('complete', 'complete'), ('qualified application', 'qualified application'), ('floor price requested', 'floor price requested'), ('floor price completed', 'floor price completed'), ('approved', 'approved'), ('denied', 'denied'), ('offer requested', 'offer requested'), ('offer submitted', 'offer submitted'), ('option period', 'option period'), ('post option', 'post option'), ('homeward purchase', 'homeward purchase'), ('customer closed', 'customer closed'), ('cancelled contract', 'cancelled contract'), ('trash', 'trash'), ("['approved', 'denied', 'offer requested', 'offer submitted', 'option period', 'post option', 'homeward purchase', 'customer closed', 'cancelled contract', 'trash']", "['approved', 'denied', 'offer requested', 'offer submitted', 'option period', 'post option', 'homeward purchase', 'customer closed', 'cancelled contract', 'trash']")], max_length=50),
        ),
        migrations.AlterField(
            model_name='stagehistory',
            name='new_stage',
            field=models.CharField(choices=[('incomplete', 'incomplete'), ('complete', 'complete'), ('qualified application', 'qualified application'), ('floor price requested', 'floor price requested'), ('floor price completed', 'floor price completed'), ('approved', 'approved'), ('denied', 'denied'), ('offer requested', 'offer requested'), ('offer submitted', 'offer submitted'), ('option period', 'option period'), ('post option', 'post option'), ('homeward purchase', 'homeward purchase'), ('customer closed', 'customer closed'), ('cancelled contract', 'cancelled contract'), ('trash', 'trash'), ("['approved', 'denied', 'offer requested', 'offer submitted', 'option period', 'post option', 'homeward purchase', 'customer closed', 'cancelled contract', 'trash']", "['approved', 'denied', 'offer requested', 'offer submitted', 'option period', 'post option', 'homeward purchase', 'customer closed', 'cancelled contract', 'trash']")], max_length=50),
        ),
        migrations.AlterField(
            model_name='stagehistory',
            name='previous_stage',
            field=models.CharField(choices=[('incomplete', 'incomplete'), ('complete', 'complete'), ('qualified application', 'qualified application'), ('floor price requested', 'floor price requested'), ('floor price completed', 'floor price completed'), ('approved', 'approved'), ('denied', 'denied'), ('offer requested', 'offer requested'), ('offer submitted', 'offer submitted'), ('option period', 'option period'), ('post option', 'post option'), ('homeward purchase', 'homeward purchase'), ('customer closed', 'customer closed'), ('cancelled contract', 'cancelled contract'), ('trash', 'trash'), ("['approved', 'denied', 'offer requested', 'offer submitted', 'option period', 'post option', 'homeward purchase', 'customer closed', 'cancelled contract', 'trash']", "['approved', 'denied', 'offer requested', 'offer submitted', 'option period', 'post option', 'homeward purchase', 'customer closed', 'cancelled contract', 'trash']")], max_length=50),
        ),
        migrations.AlterField(
            model_name='taskstatus',
            name='status',
            field=models.CharField(choices=[('Not started', 'Not started'), ('In progress', 'In progress'), ('Completed', 'Completed'), ('Under Review', 'Under Review'), ('Approved', 'Approved'), ('Denied', 'Denied')], default=application.models.task_progress.TaskProgress('Not started'), max_length=50),
        ),
    ]
