# Generated by Django 2.2 on 2020-02-13 20:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0104_auto_20200211_1442'),
    ]

    operations = [
        migrations.AddField(
            model_name='disclosure',
            name='active',
            field=models.BooleanField(default=False),
        ),
    ]
