# Generated by Django 2.2 on 2020-02-18 23:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0107_auto_20200218_2125'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='partner',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
