# Generated by Django 2.2 on 2020-02-19 18:55

from django.db import migrations
from django.db.migrations import RunPython


def add_internal_referral_detail_to_existing_apps(apps, schema_editor):
    Application = apps.get_model("application", "Application")
    Application.objects.filter(internal_referral='real-estate agent')\
        .update(internal_referral_detail='referral link')


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0109_application_internal_referral_detail'),
    ]

    operations = [
        migrations.RunPython(add_internal_referral_detail_to_existing_apps, RunPython.noop),
    ]
