# Generated by Django 2.2 on 2020-03-06 23:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0110_auto_20200219_1855'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='realestateagent',
            constraint=models.CheckConstraint(check=models.Q(('is_certified', False), ('email__isnull', False), _connector='OR'), name='required_email_certified_agent'),
        ),
    ]
