# Generated by Django 2.2 on 2020-06-02 18:49

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0113_application_questionnaire_response_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='ConvenienceFee',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True, null=True)),
                ('percentage', models.DecimalField(decimal_places=2, max_digits=4)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True, null=True)),
                ('name', models.CharField(max_length=50)),
                ('type', models.CharField(max_length=50)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.RenameField(
            model_name='preapproval',
            old_name='down_payment',
            new_name='estimated_down_payment',
        ),
        migrations.RemoveField(
            model_name='floorprice',
            name='activation',
        ),
        migrations.RemoveField(
            model_name='floorprice',
            name='expiration',
        ),
        migrations.RemoveField(
            model_name='preapproval',
            name='application',
        ),
        migrations.RemoveField(
            model_name='preapproval',
            name='decision_date',
        ),
        migrations.RemoveField(
            model_name='preapproval',
            name='expiration_date',
        ),
        migrations.RemoveField(
            model_name='preapproval',
            name='property_type',
        ),
        migrations.RemoveField(
            model_name='preapproval',
            name='reason_for_denial',
        ),
        migrations.RemoveField(
            model_name='preapproval',
            name='request_date',
        ),
        migrations.RemoveField(
            model_name='preapproval',
            name='status',
        ),
        migrations.AddField(
            model_name='application',
            name='homeward_owner_email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='application',
            name='mortgage_status',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='application',
            name='preapproval',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='application.PreApproval'),
        ),
        migrations.AddField(
            model_name='floorprice',
            name='preliminary_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='floorprice',
            name='type',
            field=models.CharField(default='No Floor Price', max_length=50),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='preapproval',
            name='amount',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True),
        ),
        migrations.CreateModel(
            name='NotificationStatus',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True, null=True)),
                ('status', models.CharField(max_length=50)),
                ('application', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='application.Application')),
                ('notification', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='application.Notification')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='application',
            name='convenience_fee',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='application.ConvenienceFee'),
        ),
    ]
