# Generated by Django 2.2 on 2020-06-02 19:04

from django.db import migrations
from django.db.migrations import RunPython


def add_internal_referral_detail_to_existing_apps(apps, schema_editor):
    Notification = apps.get_model("application", "Notification")
    Notification.objects.create(name='application under review', type='email')
    Notification.objects.create(name='approval', type='email')


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0114_auto_20200602_1849'),
    ]

    operations = [
        migrations.RunPython(add_internal_referral_detail_to_existing_apps, RunPython.noop),
    ]
