# Generated by Django 2.2 on 2020-06-02 21:13

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0115_add_notification_fixtures'),
    ]

    operations = [
        migrations.CreateModel(
            name='Rent',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True, null=True)),
                ('type', models.CharField(max_length=50)),
                ('amount_months_one_and_two', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='NewHomePurchase',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True, null=True)),
                ('convenience_fee', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('max_offer_price', models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True)),
                ('earnest_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True)),
                ('additional_deposit', models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True)),
                ('rent', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='application.Rent')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='application',
            name='new_home_purchase',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='application.NewHomePurchase'),
        ),
    ]
