# Generated by Django 2.2 on 2020-06-03 19:59

from django.db import migrations
from django.db.migrations import RunPython


def add_offer_accepted_notification(apps, schema_editor):
    Notification = apps.get_model("application", "Notification")
    Notification.objects.create(name='offer accepted', type='email')


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0117_offer_submitted_notification'),
    ]

    operations = [
        migrations.RunPython(add_offer_accepted_notification, RunPython.noop),
    ]
