# Generated by Django 2.2 on 2020-06-04 17:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0119_auto_20200603_2015'),
    ]

    operations = [
        migrations.AddField(
            model_name='newhomepurchase',
            name='contract_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True),
        ),
        migrations.AddField(
            model_name='rent',
            name='estimated_prepaid_rent',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
            preserve_default=False,
        ),
    ]
