# Generated by Django 2.2 on 2020-06-05 17:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0120_auto_20200604_1705'),
    ]

    operations = [
        migrations.AddField(
            model_name='newhomepurchase',
            name='address',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='application.Address'),
        ),
        migrations.AddField(
            model_name='newhomepurchase',
            name='earnest_deposit_percentage',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
    ]
