# Generated by Django 2.2 on 2020-06-09 15:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0121_auto_20200605_1706'),
    ]

    operations = [
        migrations.AddField(
            model_name='newhomepurchase',
            name='is_takeover',
            field=models.BooleanField(blank=True, null=True),
        ),
    ]
