# Generated by Django 2.2 on 2020-06-09 21:35

from django.db import migrations
from django.db.migrations import RunPython


def add_notification(apps, schema_editor):
    Notification = apps.get_model("application", "Notification")
    Notification.objects.create(name='agent offer instructions', type='email')


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0122_newhomepurchase_is_takeover'),
    ]

    operations = [
        migrations.RunPython(add_notification, RunPython.noop),
    ]
