# Generated by Django 2.2 on 2020-06-10 01:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0123_agent_intsructions_notification'),
    ]

    operations = [
        migrations.AddField(
            model_name='preapproval',
            name='vpal_approval_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
