# Generated by Django 2.2 on 2020-06-10 01:26

from django.db import migrations
from django.db.migrations import RunPython


def add_notification(apps, schema_editor):
    Notification = apps.get_model("application", "Notification")
    Notification.objects.create(name='expiring approval', type='email')


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0124_preapproval_vpal_approval_date'),
    ]

    operations = [
        migrations.RunPython(add_notification, RunPython.noop),
    ]
