# Generated by Django 2.2 on 2020-06-11 17:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0127_pre_homeward_close_notification'),
        ('application', '0125_auto_20200610_0126'),
    ]

    operations = [
    ]
