# Generated by Django 2.2 on 2020-06-11 17:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0128_merge_20200611_1713'),
    ]

    operations = [
        migrations.AddField(
            model_name='newhomepurchase',
            name='offer_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True),
        ),
    ]
