# Generated by Django 2.2 on 2020-06-12 17:57

from django.db import migrations
from django.db.migrations import RunPython


def add_notification(apps, schema_editor):
    Notification = apps.get_model("application", "Notification")
    Notification.objects.create(name='agent pre-homeward close', type='email')


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0129_newhomepurchase_offer_price'),
    ]

    operations = [
        migrations.RunPython(add_notification, RunPython.noop),
    ]
