# Generated by Django 2.2 on 2020-06-12 19:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0131_agent_close_notification'),
    ]

    operations = [
        migrations.AddField(
            model_name='currenthome',
            name='market_value',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True),
        ),
    ]
