# Generated by Django 2.2 on 2020-06-12 20:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0133_customer_close_notification'),
    ]

    operations = [
        migrations.AlterField(
            model_name='floorprice',
            name='amount',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True),
        ),
    ]
