# Generated by Django 2.2 on 2020-06-23 01:41

from django.db import migrations
from django.db.migrations import RunPython


def add_notifications(apps, schema_editor):
    Notification = apps.get_model("application", "Notification")
    Notification.objects.create(name='pre account one day reminder', type='email')
    Notification.objects.create(name='pre account three day reminder', type='email')
    Notification.objects.create(name='one day reminder', type='email')
    Notification.objects.create(name='three day reminder', type='email')
    Notification.objects.create(name='week reminder', type='email')
    Notification.objects.create(name='forty five min reminder', type='email')
    Notification.objects.create(name='agent referral welcome email', type='email')

class Migration(migrations.Migration):

    dependencies = [
        ('application', '0134_auto_20200612_2049'),
    ]

    operations = [
        migrations.RunPython(add_notifications, RunPython.noop),
    ]