# Generated by Django 2.2 on 2020-06-23 21:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0135_auto_20200623_0141'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='template_id',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
