# Generated by Django 2.2 on 2020-06-26 19:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0135_add_cma_request_notification'),
        ('application', '0137_auto_20200625_1820'),
    ]

    operations = [
    ]
