# Generated by Django 2.2 on 2020-06-29 17:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0138_merge_20200626_1901'),
    ]

    operations = [
        migrations.AlterField(
            model_name='application',
            name='stage',
            field=models.CharField(choices=[('incomplete', 'incomplete'), ('complete', 'complete'), ('qualified application', 'qualified application'), ('floor price requested', 'floor price requested'), ('floor price completed', 'floor price completed'), ('approved', 'approved'), ('denied', 'denied'), ('offer requested', 'offer requested'), ('offer submitted', 'offer submitted'), ('option period', 'option period'), ('post option', 'post option'), ('homeward purchase', 'homeward purchase'), ('customer closed', 'customer closed'), ('cancelled contract', 'cancelled contract'), ('trash', 'trash'), ("['incomplete', 'complete']", "['incomplete', 'complete']"), ("['qualified application', 'floor price requested', 'floor price completed', 'approved']", "['qualified application', 'floor price requested', 'floor price completed', 'approved']"), ("['approved', 'denied', 'offer requested', 'offer submitted', 'option period', 'post option', 'homeward purchase', 'customer closed', 'cancelled contract', 'trash']", "['approved', 'denied', 'offer requested', 'offer submitted', 'option period', 'post option', 'homeward purchase', 'customer closed', 'cancelled contract', 'trash']")], max_length=50),
        ),
        migrations.AlterField(
            model_name='floorprice',
            name='preliminary_amount',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True),
        ),
        migrations.AlterField(
            model_name='stagehistory',
            name='new_stage',
            field=models.CharField(choices=[('incomplete', 'incomplete'), ('complete', 'complete'), ('qualified application', 'qualified application'), ('floor price requested', 'floor price requested'), ('floor price completed', 'floor price completed'), ('approved', 'approved'), ('denied', 'denied'), ('offer requested', 'offer requested'), ('offer submitted', 'offer submitted'), ('option period', 'option period'), ('post option', 'post option'), ('homeward purchase', 'homeward purchase'), ('customer closed', 'customer closed'), ('cancelled contract', 'cancelled contract'), ('trash', 'trash'), ("['incomplete', 'complete']", "['incomplete', 'complete']"), ("['qualified application', 'floor price requested', 'floor price completed', 'approved']", "['qualified application', 'floor price requested', 'floor price completed', 'approved']"), ("['approved', 'denied', 'offer requested', 'offer submitted', 'option period', 'post option', 'homeward purchase', 'customer closed', 'cancelled contract', 'trash']", "['approved', 'denied', 'offer requested', 'offer submitted', 'option period', 'post option', 'homeward purchase', 'customer closed', 'cancelled contract', 'trash']")], max_length=50),
        ),
        migrations.AlterField(
            model_name='stagehistory',
            name='previous_stage',
            field=models.CharField(choices=[('incomplete', 'incomplete'), ('complete', 'complete'), ('qualified application', 'qualified application'), ('floor price requested', 'floor price requested'), ('floor price completed', 'floor price completed'), ('approved', 'approved'), ('denied', 'denied'), ('offer requested', 'offer requested'), ('offer submitted', 'offer submitted'), ('option period', 'option period'), ('post option', 'post option'), ('homeward purchase', 'homeward purchase'), ('customer closed', 'customer closed'), ('cancelled contract', 'cancelled contract'), ('trash', 'trash'), ("['incomplete', 'complete']", "['incomplete', 'complete']"), ("['qualified application', 'floor price requested', 'floor price completed', 'approved']", "['qualified application', 'floor price requested', 'floor price completed', 'approved']"), ("['approved', 'denied', 'offer requested', 'offer submitted', 'option period', 'post option', 'homeward purchase', 'customer closed', 'cancelled contract', 'trash']", "['approved', 'denied', 'offer requested', 'offer submitted', 'option period', 'post option', 'homeward purchase', 'customer closed', 'cancelled contract', 'trash']")], max_length=50),
        ),
    ]
