# Generated by Django 2.2 on 2020-07-22 00:20

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0140_auto_20200720_2137'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pricing',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True, null=True)),
                ('min_estimated_convenience_fee', models.DecimalField(decimal_places=2, max_digits=4)),
                ('max_estimated_convenience_fee', models.DecimalField(decimal_places=2, max_digits=4)),
                ('estimated_earnest_deposit_percentage', models.DecimalField(decimal_places=2, default=2.0, max_digits=5)),
                ('estimated_rent_amount', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
