# Generated by Django 2.2 on 2020-07-20 21:57

from django.db import migrations
from django.db.migrations import RunPython

def add_notifications(apps, schema_editor):
    Notification = apps.get_model("application", "Notification")
    Notification.objects.create(name="referral sign-up", type='email')
    Notification.objects.create(name="photo upload", type='email')

class Migration(migrations.Migration):

    dependencies = [
        ('application', '0140_auto_20200720_2137'),
    ]

    operations = [
        migrations.RunPython(add_notifications, RunPython.noop),
    ]
    
