# Generated by Django 2.2 on 2020-07-22 00:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0141_pricing'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pricing',
            old_name='max_estimated_convenience_fee',
            new_name='estimated_max_convenience_fee',
        ),
        migrations.RenameField(
            model_name='pricing',
            old_name='min_estimated_convenience_fee',
            new_name='estimated_min_convenience_fee',
        ),
    ]
