# Generated by Django 2.2 on 2020-07-22 19:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0142_auto_20200722_0034'),
        ('application', '0141_auto_20200722_1551'),
    ]

    operations = [
    ]
