# Generated by Django 2.2 on 2020-07-27 16:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0143_merge_20200722_1929'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='realestateagent',
            name='required_sf_id_certified_agent',
        ),
        migrations.RemoveConstraint(
            model_name='realestateagent',
            name='required_phone_certified_agent',
        ),
        migrations.AddField(
            model_name='currenthome',
            name='customer_value_opinion',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True),
        ),
        migrations.AddConstraint(
            model_name='realestateagent',
            constraint=models.CheckConstraint(check=models.Q(('is_certified', False), models.Q(('phone__isnull', False), models.Q(_negated=True, phone='')), _connector='OR'), name='required_phone_certified_agent'),
        ),
        migrations.AddConstraint(
            model_name='realestateagent',
            constraint=models.CheckConstraint(check=models.Q(('is_certified', False), models.Q(('sf_id__isnull', False), models.Q(_negated=True, sf_id='')), _connector='OR'), name='required_sf_id_certified_agent'),
        ),
    ]
