# Generated by Django 2.2 on 2020-07-27 17:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0144_auto_20200727_1619'),
    ]

    operations = [
        migrations.AddField(
            model_name='brokerage',
            name='logo_url',
            field=models.URLField(blank=True, null=True),
        ),
    ]
