# Generated by Django 2.2 on 2020-07-28 20:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0145_brokerage_logo_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='pricing',
            name='application',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='application.Application'),
        ),
    ]
