# Generated by Django 2.2 on 2020-07-28 21:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0146_pricing_application'),
    ]

    operations = [
        migrations.AddField(
            model_name='pricing',
            name='agent_remarks',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
