# Generated by Django 2.2 on 2020-07-31 18:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0149_pricing_agent'),
    ]

    operations = [
        migrations.AlterField(
            model_name='brokerage',
            name='sf_id',
            field=models.CharField(max_length=50, unique=True),
        ),
    ]
