# Generated by Django 2.2 on 2020-08-03 12:39

from django.db import migrations
from django.db.migrations import RunPython


def add_notification(apps, schema_editor):
    Notification = apps.get_model("application", "Notification")
    Notification.objects.create(name='agent referral complete', type='email', template_id='33142967737')


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0150_auto_20200731_1851'),
    ]

    operations = [
        migrations.RunPython(add_notification, RunPython.noop),
    ]
