# Generated by Django 2.2 on 2020-08-03 17:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0151_auto_20200803_1239'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pricing',
            name='application',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='application.Application'),
        ),
    ]
