# Generated by Django 2.2 on 2020-08-11 20:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0152_auto_20200803_1749'),
    ]

    operations = [
        migrations.AlterField(
            model_name='realestateagent',
            name='sf_id',
            field=models.CharField(default=None, max_length=50, null=True, unique=True),
        ),
    ]
