# Generated by Django 2.2 on 2020-08-19 17:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0155_auto_20200814_2025'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pricing',
            name='application',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='application.Application'),
        ),
    ]
