# Generated by Django 2.2 on 2020-08-25 20:44

from django.db import migrations
from django.db.migrations import RunPython


def add_notification(apps, schema_editor):
    Notification = apps.get_model("application", "Notification")
    Notification.objects.create(name='incomplete agent referral', type='email')


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0157_pricing_questionnaire_response_id'),
    ]

    operations = [
        migrations.RunPython(add_notification, RunPython.noop),
    ]
