# Generated by Django 2.2 on 2020-08-25 21:56

from django.db import migrations
from django.db.migrations import RunPython


def modify_notification(apps, schema_editor):
    Notification = apps.get_model("application", "Notification")
    notification = Notification.objects.get(name='incomplete agent referral')
    notification.name = 'incomplete referral'
    notification.save()


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0158_incomplete_referral_notification'),
    ]

    operations = [
        migrations.RunPython(modify_notification, RunPython.noop),
    ]
