# Generated by Django 2.2 on 2020-09-08 18:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0159_auto_20200825_2156'),
    ]

    operations = [
        migrations.AddField(
            model_name='disclosure',
            name='buying_agent_brokerage',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='disclosure',
            name='disclosure_type',
            field=models.CharField(choices=[('title', 'title'), ('mortgage', 'mortgage'), ('service_agreement', 'service_agreement')], default='Invalid', max_length=50),
            preserve_default=False,
        ),
    ]
