# Generated by Django 2.2 on 2020-09-09 15:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0160_auto_20200908_1856'),
    ]

    operations = [
        migrations.AddField(
            model_name='pricing',
            name='estimated_max_rent_amount',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='pricing',
            name='estimated_min_rent_amount',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
            preserve_default=False,
        ),
    ]
