# Generated by Django 2.2 on 2020-09-09 15:34

from django.db import migrations
from django.db.migrations import RunPython


def convert_rent_to_min_max(apps, schema_editor):
    Pricing = apps.get_model("application", "Pricing")
    pricing_objects = Pricing.objects.all()
    for pricing in pricing_objects:
        pricing.estimated_min_rent_amount = pricing.estimated_rent_amount
        pricing.estimated_max_rent_amount = pricing.estimated_rent_amount
        pricing.save()


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0161_auto_20200909_1534'),
    ]

    operations = [
        migrations.RunPython(convert_rent_to_min_max, RunPython.noop, elidable=True),
    ]
