# Generated by Django 2.2 on 2020-09-09 18:49

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0162_migrate_rent_to_min_max'),
    ]

    operations = [
        migrations.AddField(
            model_name='pricing',
            name='actions',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=10), default=list, size=None),
        ),
    ]
