# Generated by Django 2.2 on 2020-09-09 20:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0163_pricing_actions'),
    ]

    operations = [
        migrations.AddField(
            model_name='pricing',
            name='agent_situation',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
