# Generated by Django 2.2 on 2020-09-15 15:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0165_saved_quote_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='co_borrower_email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
    ]
