# Generated by Django 2.2 on 2020-09-28 21:19

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0166_customer_co_borrower_email'),
    ]

    operations = [
        migrations.RenameField(
            model_name='currenthome',
            old_name='close_date',
            new_name='closing_date',
        ),
        migrations.AddField(
            model_name='currenthome',
            name='addition_size_sq_ft',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='currenthome',
            name='addition_type',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='currenthome',
            name='back_yard_condition',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='currenthome',
            name='basement_size_sq_ft',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='currenthome',
            name='basement_type',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='currenthome',
            name='bedrooms_count',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='currenthome',
            name='carpet_flooring_condition',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='currenthome',
            name='customer_notes',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='currenthome',
            name='exterior_walls_types',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(blank=True, max_length=50, null=True), blank=True, null=True, size=None),
        ),
        migrations.AddField(
            model_name='currenthome',
            name='flooring_types',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(blank=True, max_length=50, null=True), blank=True, null=True, size=None),
        ),
        migrations.AddField(
            model_name='currenthome',
            name='floors_count',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='currenthome',
            name='front_yard_condition',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='currenthome',
            name='full_bathrooms_count',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='currenthome',
            name='garage_spaces_count',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='currenthome',
            name='hardwood_flooring_condition',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='currenthome',
            name='has_basement',
            field=models.NullBooleanField(),
        ),
        migrations.AddField(
            model_name='currenthome',
            name='has_made_addition',
            field=models.NullBooleanField(),
        ),
        migrations.AddField(
            model_name='currenthome',
            name='home_features',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(blank=True, max_length=50, null=True), blank=True, null=True, size=None),
        ),
        migrations.AddField(
            model_name='currenthome',
            name='home_size_sq_ft',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='currenthome',
            name='hvac_age_range',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='currenthome',
            name='in_floodzone',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='currenthome',
            name='interior_walls_condition',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='currenthome',
            name='kitchen_appliance_type',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='currenthome',
            name='kitchen_countertop_type',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='currenthome',
            name='kitchen_features',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(blank=True, max_length=50, null=True), blank=True, null=True, size=None),
        ),
        migrations.AddField(
            model_name='currenthome',
            name='kitchen_has_been_remodeled',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='currenthome',
            name='listing_status',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='currenthome',
            name='listing_url',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='currenthome',
            name='master_bathroom_condition',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='currenthome',
            name='master_on_main',
            field=models.NullBooleanField(),
        ),
        migrations.AddField(
            model_name='currenthome',
            name='option_period_expiration_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='currenthome',
            name='partial_bathrooms_count',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='currenthome',
            name='pool_type',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='currenthome',
            name='property_view_type',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='currenthome',
            name='repair_or_update_detail',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='currenthome',
            name='roof_age_range',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='currenthome',
            name='sides_with_masonry_count',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='currenthome',
            name='total_concession_amount',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True),
        ),
        migrations.AddField(
            model_name='currenthome',
            name='under_contract_sales_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True),
        ),
    ]
