# Generated by Django 2.2 on 2020-10-22 16:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0168_auto_20201006_2136'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pricing',
            name='estimated_rent_amount',
        ),
        migrations.AddField(
            model_name='pricing',
            name='agents_company',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='pricing',
            name='buying_location',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='buying_location_pricing', to='application.Address'),
        ),
        migrations.AddField(
            model_name='pricing',
            name='max_price',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='pricing',
            name='min_price',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='pricing',
            name='selling_location',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='selling_location_pricing', to='application.Address'),
        ),
        migrations.AlterField(
            model_name='currenthomeimage',
            name='label',
            field=models.TextField(blank=True, choices=[('kitchen', 'kitchen'), ('living_room', 'living_room'), ('master_bath', 'master_bath'), ('front_exterior', 'front_exterior'), ('all_other_rooms', 'all_other_rooms'), ('required_repairs', 'required_repairs'), ('home_updates', 'home_updates')], null=True),
        ),
    ]
