# Generated by Django 2.2 on 2020-10-26 16:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0169_auto_20201022_1658'),
    ]

    operations = [
        migrations.AddField(
            model_name='application',
            name='product_offering',
            field=models.TextField(default='buy-sell'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='disclosure',
            name='product_offering',
            field=models.TextField(blank=True, null=True),
        ),
    ]
