# Generated by Django 2.2 on 2020-10-23 18:39

from django.db import migrations
from django.db.migrations import RunPython


def add_buy_only_disclosures(apps, schema_editor):
    Disclosure = apps.get_model("application", "Disclosure")

    for disclosure in Disclosure.objects.filter(disclosure_type='service_agreement'):
        disclosure.product_offering = 'buy-sell'
        disclosure.save()

    common_params = {
        'disclosure_type': 'service_agreement',
        'active': True,
        'product_offering': 'buy-only'
    }

    Disclosure.objects.create(name="service agreement (texas - buy only)",
                              document_url='https://storage.googleapis.com/acknowledgeable_documents/Service-Agreement-Texas.pdf',
                              buying_state='tx',
                              **common_params)
    Disclosure.objects.create(name="service agreement (texas realty austin - buy only)",
                              document_url='https://storage.googleapis.com/acknowledgeable_documents/Service-Agreement-Texas.pdf',
                              buying_agent_brokerage='Realty Austin',
                              buying_state='tx',
                              **common_params)
    Disclosure.objects.create(name="service agreement (colorado - buy only)",
                              document_url='https://storage.googleapis.com/acknowledgeable_documents/Service-Agreement-Colorado.pdf',
                              buying_state='co',
                              **common_params)
    Disclosure.objects.create(name="service agreement (georgia - buy only)",
                              document_url='https://storage.googleapis.com/acknowledgeable_documents/Service-Agreement-Georgia-V2.pdf',
                              buying_state='ga',
                              **common_params)
    return


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0170_auto_20201026_1607'),
    ]

    operations = [
        migrations.RunPython(add_buy_only_disclosures, RunPython.noop),
    ]
