# Generated by Django 2.2 on 2020-10-26 18:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0171_add_buy_only_disclosures'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='disclosure',
            constraint=models.UniqueConstraint(fields=('buying_state', 'selling_state', 'buying_agent_brokerage', 'active', 'product_offering'), name='unique_buying_selling_brokerage_active_offering'),
        ),
    ]
