# Generated by Django 2.2 on 2020-11-13 21:26

import django.contrib.postgres.fields.jsonb
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0174_auto_20201113_1523'),
    ]

    operations = [
        migrations.AddField(
            model_name='pricing',
            name='utm',
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, default=dict, null=True),
        ),
    ]
