# Generated by Django 2.2 on 2020-11-16 19:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0175_pricing_utm'),
    ]

    operations = [
        migrations.AddField(
            model_name='notificationstatus',
            name='reason',
            field=models.TextField(blank=True, null=True),
        ),
    ]
