# Generated by Django 2.2 on 2020-11-17 15:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0176_notificationstatus_reason'),
    ]

    operations = [
        migrations.AddField(
            model_name='application',
            name='is_reassigned_contract',
            field=models.BooleanField(default=False),
        ),
    ]
