# Generated by Django 2.2 on 2020-12-18 18:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0177_application_is_reassigned_contract'),
    ]

    operations = [
        migrations.AlterField(
            model_name='currenthome',
            name='repair_or_update_detail',
            field=models.TextField(blank=True, null=True),
        ),
    ]
