# Generated by Django 2.2 on 2020-12-22 17:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0178_auto_20201218_1838'),
    ]

    operations = [
        migrations.AddField(
            model_name='pricing',
            name='product_offering',
            field=models.TextField(default='buy-sell'),
        ),
    ]
