# Generated by Django 2.2 on 2020-12-22 21:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0179_pricing_product_offering'),
    ]

    operations = [
        migrations.AlterField(
            model_name='disclosure',
            name='document_url',
            field=models.TextField(),
        ),
    ]
