# Generated by Django 2.2 on 2020-12-30 20:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0182_auto_20201228_1733'),
    ]

    operations = [
        migrations.AlterField(
            model_name='currenthome',
            name='customer_notes',
            field=models.TextField(blank=True, null=True),
        ),
    ]
