# Generated by Django 2.2 on 2021-01-12 21:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0183_auto_20201230_2029'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pricing',
            name='agent_remarks',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='pricing',
            name='agent_situation',
            field=models.TextField(blank=True, null=True),
        ),
    ]
