# Generated by Django 2.2 on 2021-01-18 20:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0184_auto_20210112_2144'),
    ]

    operations = [
        migrations.AlterField(
            model_name='application',
            name='agent_notes',
            field=models.TextField(blank=True, null=True),
        ),
    ]
