# Generated by Django 2.2 on 2021-01-25 22:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0185_auto_20210118_2041'),
    ]

    operations = [
        migrations.AddField(
            model_name='pricing',
            name='salesforce_id',
            field=models.TextField(blank=True, null=True),
        ),
    ]
