# Generated by Django 2.2 on 2021-02-09 22:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0187_cxmanager_phone'),
    ]

    operations = [
        migrations.AddField(
            model_name='application',
            name='agent_client_contact_preference',
            field=models.TextField(blank=True, null=True),
        ),
    ]
