# Generated by Django 2.2 on 2021-02-24 15:39

import application.models.application
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0190_vpal_incomplete_notification'),
    ]

    operations = [
        migrations.AddField(
            model_name='application',
            name='hw_mortgage_candidate',
            field=models.CharField(choices=[('Yes - Not Required', 'Yes - Not Required'), ('Yes - Required', 'Yes - Required'), ('No', 'No'), ('Not Deteremined', 'Not Deteremined')], default='Not Deteremined', max_length=50),
        ),
    ]
