# Generated by Django 2.2 on 2021-02-24 19:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0191_application_hw_mortgage_candidate'),
        ('application', '0191_auto_20210223_2143'),
    ]

    operations = [
    ]
