# Generated by Django 2.2 on 2021-02-24 20:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0191_application_hw_mortgage_candidate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='application',
            name='hw_mortgage_candidate',
            field=models.CharField(choices=[('Yes - Not Required', 'Yes - Not Required'), ('Yes - Required', 'Yes - Required'), ('No', 'No'), ('Not Determined', 'Not Determined')], default='Not Determined', max_length=50),
        ),
    ]
