# Generated by Django 2.2 on 2021-02-24 22:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0192_merge_20210224_1923'),
        ('application', '0192_auto_20210224_2007'),
    ]

    operations = [
    ]
