# Generated by Django 2.2 on 2021-02-24 19:04

from django.db import migrations
from django.db.migrations import RunPython


def add_notification(apps, schema_editor):
    Notification = apps.get_model("application", "Notification")
    Notification.objects.create(name='VPAL Ready for Review', type='email')


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0192_auto_20210224_2007'),
    ]

    operations = [
        migrations.RunPython(add_notification, RunPython.noop),
    ]
