# Generated by Django 2.2 on 2021-02-25 14:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0193_merge_20210224_2259'),
        ('application', '0193_vpal_ready_for_review'),
    ]

    operations = [
    ]
