# Generated by Django 2.2 on 2021-03-02 17:34

from django.db import migrations
from django.db.migrations import RunPython


def add_notification(apps, schema_editor):
    Notification = apps.get_model("application", "Notification")
    Notification.objects.create(name='apex site pre account', type='email')

class Migration(migrations.Migration):

    dependencies = [
        ('application', '0194_merge_20210225_1452'),
    ]

    operations = [
        migrations.RunPython(add_notification, RunPython.noop),
    ]
