# Generated by Django 2.2 on 2021-02-25 22:40

from django.db import migrations
from django.db.migrations import RunPython

def add_notification(apps, schema_editor):
    Notification = apps.get_model("application", "Notification")
    Notification.objects.create(name='homeward mortgage candidiate approval', type='email')


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0194_merge_20210225_1452'),
    ]

    operations = [
        migrations.RunPython(add_notification, RunPython.noop),
    ]
