# Generated by Django 2.2 on 2021-03-01 21:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0195_auto_20210225_2240'),
    ]

    operations = [
        migrations.AddField(
            model_name='preapproval',
            name='hw_mortgage_conditions',
            field=models.TextField(blank=True, null=True),
        ),
    ]
