# Generated by Django 2.2 on 2021-03-02 18:18

from django.db import migrations
from django.db.migrations import RunPython

def add_notification(apps, schema_editor):
    Notification = apps.get_model("application", "Notification")
    Notification.objects.create(name='VPAL Ready for Review Follow up', type='email')

class Migration(migrations.Migration):

    dependencies = [
        ('application', '0195_auto_20210225_2240'),
    ]

    operations = [
        migrations.RunPython(add_notification, RunPython.noop),
    ]
