# Generated by Django 2.2 on 2021-03-02 22:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0195_auto_20210302_1734'),
        ('application', '0196_preapproval_hw_mortgage_conditions'),
    ]

    operations = [
    ]
