# Generated by Django 2.2 on 2021-03-04 16:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0197_merge_20210302_2238'),
        ('application', '0196_auto_20210302_1818'),
    ]

    operations = [
    ]
