# Generated by Django 2.2 on 2021-03-09 19:07

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0198_merge_20210304_1629'),
    ]

    operations = [
        migrations.CreateModel(
            name='Offer',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True, null=True)),
                ('year_built', models.IntegerField(blank=True, null=True)),
                ('home_square_footage', models.IntegerField(blank=True, null=True)),
                ('property_type', models.CharField(choices=[('Single Family', 'Single Family'), ('Multi-Family', 'Multi-Family'), ('Luxury', 'Luxury'), ('Condo', 'Condo'), ('Lot', 'Lot')], max_length=50)),
                ('less_than_one_acre', models.BooleanField(default=False)),
                ('home_list_price', models.IntegerField(blank=True, null=True)),
                ('offer_price', models.IntegerField(blank=True, null=True)),
                ('contract_type', models.CharField(choices=[('Resale', 'Resale'), ('New Build', 'New Build')], max_length=50)),
                ('other_offers', models.CharField(choices=[('No', 'No'), ('1-4', '1-4'), ('5+', '5+')], max_length=50)),
                ('offer_deadline', models.DateTimeField(blank=True, null=True)),
                ('plan_to_lease_back_to_seller', models.CharField(choices=[('No', 'No'), ('Yes', 'Yes'), ('Not Sure', 'Not Sure')], max_length=50)),
                ('waive_appraisal', models.BooleanField(default=False)),
                ('already_under_contract', models.BooleanField(default=False)),
                ('comments', models.TextField(blank=True, null=True)),
                ('application', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='offers', to='application.Application')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
