# Generated by Django 2.2 on 2021-03-11 22:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0199_offer'),
    ]

    operations = [
        migrations.AddField(
            model_name='offer',
            name='offer_property_address',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='offers', to='application.Address'),
        ),
    ]
