# Generated by Django 2.2 on 2021-03-18 17:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0201_offer_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='offer',
            name='salesforce_id',
            field=models.TextField(blank=True, null=True),
        ),
    ]
