# Generated by Django 2.2 on 2021-03-22 16:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0202_offer_salesforce_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='offer',
            name='contract_type',
            field=models.CharField(blank=True, choices=[('Resale', 'Resale'), ('New Build', 'New Build')], max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='offer',
            name='other_offers',
            field=models.CharField(blank=True, choices=[('No', 'No'), ('1-4', '1-4'), ('5+', '5+')], max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='offer',
            name='plan_to_lease_back_to_seller',
            field=models.CharField(blank=True, choices=[('No', 'No'), ('Yes', 'Yes'), ('Not Sure', 'Not Sure')], max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='offer',
            name='property_type',
            field=models.CharField(blank=True, choices=[('Single Family', 'Single Family'), ('Multi-Family', 'Multi-Family'), ('Luxury', 'Luxury'), ('Condo', 'Condo'), ('Lot', 'Lot')], max_length=50, null=True),
        ),
    ]
