# Generated by Django 2.2 on 2021-03-26 14:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0204_loan'),
    ]

    operations = [
        migrations.AlterField(
            model_name='offer',
            name='waive_appraisal',
            field=models.CharField(blank=True, choices=[('Not eligible', 'Not eligible'), ('Yes', 'Yes'), ('No - not comfortable covering any delta', 'No - not comfortable covering any delta'), ('No - only comfortable covering partial delta', 'No - only comfortable covering partial delta'), ('No - undecided on covering delta & wants to know value first', 'No - undecided on covering delta & wants to know value first'), ('No - Other', 'No - Other')], max_length=100, null=True),
        ),
    ]
