# Generated by Django 2.2 on 2021-03-26 16:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0205_auto_20210326_1405'),
    ]

    operations = [
        migrations.AddField(
            model_name='offer',
            name='listing_id',
            field=models.UUIDField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='offer',
            name='less_than_one_acre',
            field=models.BooleanField(blank=True, null=True),
        ),
    ]
