# Generated by Django 2.2 on 2021-03-30 15:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0206_auto_20210326_1659'),
    ]

    operations = [
        migrations.AlterField(
            model_name='offer',
            name='salesforce_id',
            field=models.TextField(blank=True, null=True, unique=True),
        ),
    ]
