# Generated by Django 2.2 on 2021-03-31 14:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0208_auto_20210330_1652'),
    ]

    operations = [
        migrations.AddField(
            model_name='application',
            name='apex_partner_slug',
            field=models.TextField(blank=True, null=True),
        ),
    ]
