# Generated by Django 2.2 on 2021-04-12 22:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0211_auto_20210412_2159'),
        ('application', '0211_auto_20210412_2221'),
    ]

    operations = [
    ]
