# Generated by Django 2.2 on 2021-04-21 14:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0212_merge_20210412_2240'),
    ]

    operations = [
        migrations.AddField(
            model_name='offer',
            name='offer_source',
            field=models.TextField(blank=True, null=True),
        ),
    ]
