# Generated by Django 2.2 on 2021-04-23 00:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0213_offer_offer_source'),
    ]

    operations = [
        migrations.RenameField(
            model_name='offer',
            old_name='listing_id',
            new_name='pda_listing_uuid',
        ),
        migrations.AddField(
            model_name='offer',
            name='mls_listing_id',
            field=models.TextField(blank=True, null=True),
        ),
    ]
