 # Generated by Django 2.2 on 2021-04-27 14:23

from django.db import migrations
from django.db.migrations import RunPython


def add_notification(apps, schema_editor):
    Notification = apps.get_model("application", "Notification")
    Notification.objects.create(name='offer submitted agent', type='email')


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0213_offer_offer_source'),
    ]

    operations = [
        migrations.RunPython(add_notification, RunPython.noop),
    ]
