# Generated by Django 2.2 on 2021-04-29 15:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0214_auto_20210423_0004'),
        ('application', '0214_offer_submitted_agent_notification'),
    ]

    operations = [
    ]
