# Generated by Django 2.2 on 2021-04-29 18:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0215_merge_20210429_1506'),
    ]

    operations = [
        migrations.AlterField(
            model_name='offer',
            name='preferred_closing_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
