# Generated by Django 2.2 on 2021-04-29 21:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0214_auto_20210429_1345'),
        ('application', '0216_auto_20210429_1816'),
    ]

    operations = [
    ]
