# Generated by Django 2.2 on 2021-05-05 14:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0218_auto_20210503_2036'),
    ]

    operations = [
        migrations.AlterField(
            model_name='disclosure',
            name='disclosure_type',
            field=models.CharField(choices=[('title', 'title'), ('mortgage', 'mortgage'), ('service_agreement', 'service_agreement'), ('e_consent', 'e_consent')], max_length=50),
        ),
    ]
