# Generated by Django 2.2 on 2021-05-13 15:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0219_auto_20210505_1457'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='application',
            index=models.Index(fields=['new_salesforce'], name='application_new_sal_737916_idx'),
        ),
    ]
