# Generated by Django 2.2 on 2021-05-13 15:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0220_auto_20210513_1510'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='realestateagent',
            index=models.Index(fields=['email'], name='application_email_70bf9d_idx'),
        ),
        migrations.AddIndex(
            model_name='realestateagent',
            index=models.Index(fields=['phone'], name='application_phone_d5253a_idx'),
        ),
        migrations.AddIndex(
            model_name='realestateagent',
            index=models.Index(fields=['sf_id'], name='application_sf_id_784797_idx'),
        ),
    ]
