# Generated by Django 2.2 on 2021-05-17 18:15

from django.db import migrations, models
from django.db.migrations import RunPython


def modify_notifications(apps, schema_editor):
    Notification = apps.get_model("application", "Notification")
    notifications = Notification.objects.all()
    for notification in notifications:
        notification.is_active = True
        notification.save()


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0221_auto_20210513_1517'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='is_active',
            field=models.BooleanField(default=False),
        ),
        migrations.RunPython(modify_notifications, RunPython.noop),
    ]
