# Generated by Django 2.2 on 2021-05-19 15:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0222_notification_is_active'),
    ]

    operations = [
        migrations.AlterField(
            model_name='offer',
            name='status',
            field=models.TextField(choices=[('Incomplete', 'Incomplete'), ('Complete', 'Complete'), ('Requested', 'Requested'), ('MOP Complete', 'MOP Complete'), ('Approved', 'Approved'), ('Backup Position Accepted', 'Backup Position Accepted'), ('Denied', 'Denied'), ('Won', 'Won'), ('Lost', 'Lost'), ('Cancelled', 'Cancelled'), ('Contract Cancelled', 'Contract Cancelled')], default='Incomplete'),
        ),
    ]
