# Generated by Django 2.2 on 2021-06-03 12:37

from django.db import migrations, models
from django.db.migrations import RunPython
from application.models.acknowledgement import Acknowledgement

def update_acknowledgement_acknowledged_at(apps, schema_editor):
    acknowledgements = Acknowledgement.objects.filter(acknowledged_at= None, is_acknowledged=True)
    for acknowledgement in acknowledgements:
        acknowledgement.acknowledged_at = acknowledgement.updated_at
        acknowledgement.save()

class Migration(migrations.Migration):

    dependencies = [
        ('application', '0223_auto_20210519_1548'),
    ]

    operations = [
        migrations.AddField(
            model_name='acknowledgement',
            name='acknowledged_at',
            field=models.DateTimeField(blank=True, default=None, null=True),
        ),
        migrations.RunPython(update_acknowledgement_acknowledged_at, RunPython.noop)
    ]
