# Generated by Django 2.2 on 2021-06-02 19:25

import application.models.stakeholder_type
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0223_auto_20210519_1548'),
    ]

    operations = [
        migrations.CreateModel(
            name='Stakeholder',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True, null=True)),
                ('email', models.TextField(max_length=50)),
                ('type', models.TextField(choices=[('transaction coordinator', 'transaction coordinator')], max_length=50)),
                ('application', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stakeholders', to='application.Application')),
            ],
        ),
        migrations.AddConstraint(
            model_name='stakeholder',
            constraint=models.UniqueConstraint(condition=models.Q(type=application.models.stakeholder.StakeholderType('transaction coordinator')), fields=('application',), name='unique_transaction_coordinator_application'),
        ),
    ]
