# Generated by Django 2.2 on 2021-06-03 17:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0224_acknowledgement_acknowledged_at'),
        ('application', '0224_auto_20210602_1925'),
    ]

    operations = [
    ]
