# Generated by Django 2.2 on 2021-06-21 15:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0226_auto_20210617_1144'),
    ]

    operations = [
        migrations.RenameField(
            model_name='loan',
            old_name='estimated_convenience_fee_discount',
            new_name='estimated_mortgage_convenience_fee_credit',
        ),
    ]
