# Generated by Django 2.2 on 2021-06-25 19:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0227_auto_20210621_1541'),
    ]

    operations = [
        migrations.AddField(
            model_name='currenthome',
            name='anything_needs_repairs',
            field=models.NullBooleanField(),
        ),
        migrations.AddField(
            model_name='currenthome',
            name='made_repairs_or_updates',
            field=models.NullBooleanField(),
        ),
    ]
