# Generated by Django 2.2 on 2021-06-22 15:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0227_auto_20210621_1541'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='application',
            name='convenience_fee',
        ),
        migrations.RemoveField(
            model_name='newhomepurchase',
            name='convenience_fee',
        ),
        migrations.DeleteModel(
            name='ConvenienceFee',
        ),
    ]
