# Generated by Django 2.2.24 on 2021-07-13 23:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0228_auto_20210625_1936'),
    ]

    operations = [
        migrations.AddField(
            model_name='offer',
            name='hoa',
            field=models.BooleanField(blank=True, null=True),
        ),
    ]
