# Generated by Django 2.2.24 on 2021-07-19 15:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0229_offer_hoa'),
    ]

    operations = [
        migrations.AlterField(
            model_name='loan',
            name='estimated_broker_convenience_fee_credit',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='loan',
            name='estimated_mortgage_convenience_fee_credit',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
