# Generated by Django 2.2.24 on 2021-07-19 19:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0230_auto_20210719_1519'),
        ('application', '0228_auto_20210622_1513'),
    ]

    operations = [
    ]
