# Generated by Django 2.2.24 on 2021-07-29 16:24

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0231_merge_20210719_1925'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContractTemplate',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True, null=True)),
                ('filename', models.CharField(default=None, max_length=1024, null=True)),
                ('buying_state', models.CharField(choices=[('TX', 'TX'), ('GA', 'GA')], max_length=2)),
                ('property_type', models.CharField(choices=[('Single Family', 'Single Family'), ('Multi-Family', 'Multi-Family'), ('Luxury', 'Luxury'), ('Condo', 'Condo'), ('Lot', 'Lot'), ('Other', 'Other')], max_length=50)),
                ('contract_type', models.CharField(choices=[('Resale', 'Resale'), ('New Build', 'New Build')], max_length=50)),
                ('active', models.BooleanField(default=False)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
