# Generated by Django 2.2.24 on 2021-07-27 14:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0231_merge_20210719_1925'),
    ]

    operations = [
        migrations.AddField(
            model_name='offer',
            name='finance_approved_close_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='offer',
            name='funding_type',
            field=models.TextField(blank=True, null=True),
        ),
    ]
