# Generated by Django 2.2.24 on 2021-08-02 19:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0232_contracttemplate'),
        ('application', '0232_auto_20210727_1432'),
    ]

    operations = [
    ]
