# Generated by Django 2.2.24 on 2021-08-03 13:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0233_merge_20210802_1948'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rent',
            name='estimated_prepaid_rent',
        ),
        migrations.AddField(
            model_name='rent',
            name='daily_rental_rate',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='rent',
            name='total_leaseback_credit',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='rent',
            name='total_waived_rent',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='newhomepurchase',
            name='rent',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='new_home_purchase', to='application.Rent'),
        ),
    ]
