# Generated by Django 2.2.24 on 2021-08-03 20:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0234_auto_20210803_1326'),
    ]

    operations = [
        migrations.AddField(
            model_name='loan',
            name='estimated_daily_rent',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='loan',
            name='estimated_monthly_rent',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
