# Generated by Django 2.2.24 on 2021-08-05 20:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0235_auto_20210803_2020'),
    ]

    operations = [
        migrations.AddField(
            model_name='application',
            name='salesforce_company_id',
            field=models.TextField(blank=True, null=True),
        ),
    ]
