# Generated by Django 2.2.24 on 2021-08-06 17:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0236_application_salesforce_company_id'),
        ('application', '0236_offer_office_name'),
    ]

    operations = [
    ]
