# Generated by Django 2.2.24 on 2021-08-11 14:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0237_merge_20210806_1727'),
    ]

    operations = [
        migrations.AddField(
            model_name='rent',
            name='stop_rent_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
