# Generated by Django 2.2.24 on 2021-08-18 15:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0238_rent_stop_rent_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='loan',
            name='approval_specialist',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='approval_specialist', to='application.InternalSupportUser'),
        ),
    ]
