# Generated by Django 2.2.24 on 2021-09-01 16:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0240_auto_20210820_1541'),
    ]

    operations = [
        migrations.AlterField(
            model_name='internalsupportuser',
            name='bio',
            field=models.TextField(blank=True, max_length=1000, null=True),
        ),
    ]
