# Generated by Django 2.2.24 on 2021-09-02 17:51

from django.db import migrations
from django.db.migrations import RunPython


def add_az_service_agreements(apps, schema_editor):
    Disclosure = apps.get_model("application", "Disclosure")

    Disclosure.objects.create(name="service agreement (az - buy-sell)",
                              document_url='https://storage.googleapis.com/acknowledgeable_documents/Service-Agreement-Texas.pdf',
                              buying_state='az',
                              disclosure_type='service_agreement',
                              active=False,
                              product_offering='buy-sell')

    Disclosure.objects.create(name="service agreement (az - buy only)",
                              document_url='https://storage.googleapis.com/acknowledgeable_documents/Service-Agreement-Texas.pdf',
                              buying_state='az',
                              disclosure_type='service_agreement',
                              active=False,
                              product_offering='buy-only')


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0241_auto_20210901_1652'),
    ]

    operations = [
        migrations.RunPython(add_az_service_agreements, RunPython.noop),
    ]
