# Generated by Django 2.2.24 on 2021-09-02 19:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0242_add_service_agreements_for_az'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='name',
            field=models.CharField(max_length=50, unique=True),
        ),
    ]
