# Generated by Django 2.2.24 on 2021-09-08 16:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0243_auto_20210902_1917'),
    ]

    operations = [
        migrations.AddField(
            model_name='application',
            name='filter_status',
            field=models.TextField(blank=True, null=True),
        ),
    ]
