# Generated by Django 2.2.24 on 2021-09-09 13:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0244_application_filter_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='newhomepurchase',
            name='additional_deposit',
        ),
        migrations.RemoveField(
            model_name='newhomepurchase',
            name='max_offer_price',
        ),
        migrations.RemoveField(
            model_name='newhomepurchase',
            name='offer_price',
        ),
    ]
