# Generated by Django 2.2.24 on 2021-09-10 17:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0245_auto_20210909_1351'),
        ('application', '0245_remove_newhomepurchase_is_takeover'),
    ]

    operations = [
    ]
