# Generated by Django 2.2.24 on 2021-09-13 17:33

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0245_auto_20210913_1731'),
    ]

    operations = [
        migrations.AddField(
            model_name='application',
            name='filter_status',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(blank=True, choices=[('Archived', 'Archived')], max_length=10, null=True), default=list, size=None),
        ),
    ]
