# Generated by Django 2.2.24 on 2021-09-13 17:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0246_application_filter_status'),
        ('application', '0245_remove_newhomepurchase_is_takeover'),
    ]

    operations = [
    ]
