# Generated by Django 2.2.24 on 2021-09-13 21:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0246_merge_20210910_1702'),
        ('application', '0247_merge_20210913_1742'),
    ]

    operations = [
    ]
