# Generated by Django 2.2.24 on 2021-09-15 13:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0249_offer_new_home_purchase'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='newhomepurchase',
            name='earnest_amount',
        ),
    ]
