# Generated by Django 2.2.24 on 2021-09-15 15:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0250_remove_newhomepurchase_earnest_amount'),
    ]

    operations = [
        migrations.AddField(
            model_name='loan',
            name='estimated_earnest_deposit_percentage',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
    ]
