# Generated by Django 2.2.24 on 2021-09-15 18:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0251_loan_estimated_earnest_deposit_percentage'),
    ]

    operations = [
        migrations.AddField(
            model_name='newhomepurchase',
            name='homeward_purchase_status',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='newhomepurchase',
            name='is_reassigned_contract',
            field=models.BooleanField(default=False),
        ),
    ]
