# Generated by Django 2.2.24 on 2021-09-23 17:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0252_auto_20210915_1809'),
    ]

    operations = [
        migrations.AlterField(
            model_name='offer',
            name='finance_approved_close_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
