# Generated by Django 2.2.24 on 2021-09-27 18:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0252_auto_20210915_1809'),
    ]

    operations = [
        migrations.AddField(
            model_name='application',
            name='agent_service_buying_agent_id',
            field=models.TextField(blank=True, null=True),
        ),
    ]
