# Generated by Django 2.2.24 on 2021-09-24 13:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0253_auto_20210923_1719'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='application',
            name='is_reassigned_contract',
        ),
    ]
