# Generated by Django 2.2.24 on 2021-09-30 17:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0254_remove_application_is_reassigned_contract'),
        ('application', '0253_application_agent_service_buying_agent_id'),
    ]

    operations = [
    ]
